title: Gael Pentang
logo: /assets/img/MyPic_Circle.png
description: Personal Web Page
show_downloads: false
theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
# other themes: Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
